### ISSUE TITLE
[Refactor] API Design

### ISSUE THREAD

**Issue by DyeKuu** [sail-sg/jax_xc#19]
The input args `polarized` and `rho` are coupled, could we not specify the polarization and deduce from the spec of `rho`?

However, we need the `polarized` argument as a concrete variable to pass into libxc to get the internal parameters. Letting it delay after the trace time means that we will be calling libxc then and I doubt that it will be not working.

The input args `rho` is also coupled with `mo`.

**Comment by mavenlin** [comment]
Also, I think if we don't properly pass polarized during the construction of internal parameter, it could have the risk of getting a wrong internal parameter

**Comment by mavenlin** [comment]
`jax.eval_shape` should be able to solve this problem.

**Comment by mavenlin** [comment]
Resolved in experimental api in #34
