### ISSUE TITLE
Automate RTD pipeline in release workflow

### ISSUE THREAD

**Issue by mavenlin** [sail-sg/jax_xc#3]
After building the wheel

1. Install the wheel.
2. Invoke sphinx make html.
3. Deploy to readthedocs.

**Comment by mavenlin** [comment]
Could you assist @DyeKuu on this?

> I believe the steps should be:
> 
> 1. Create a RTD account
> 2. Connect GitHub account to RTD
> 3. Import a project
> 4. Set up an [Integration](https://docs.readthedocs.io/en/stable/integrations.html) so RTD automatically builds on detecting changes

**Comment by DyeKuu** [comment]
It seems that I need an `admin` permission to add a webhook for this repo:

https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

https://docs.readthedocs.io/en/latest/integrations.html

**Comment by mavenlin** [comment]
RTD online 

https://jax-xc.readthedocs.io/en/latest/
