### ISSUE TITLE
Cannot find the package or file autofd

### ISSUE THREAD

**Issue by faro1219** [sail-sg/jax_xc#33]
I want to use the experimental function to find the functional derivative. However, I cannot install the package autofd or find the file autofd.

**Comment by DyeKuu** [comment]
Hi @faro1219 ! The release note says that "This release adds experimental support for functional derivative, currently awaiting autofd to release." That's a separate package designed to serve as a paper-level code while under review so I guess it still needs time.

cc @mavenlin

**Comment by mavenlin** [comment]
autofd is released now, and version jax_xc version 0.0.9 has integrated the support.
