### ISSUE TITLE
Exposing energy densities

### ISSUE THREAD

**Issue by jackbaker1001** [sail-sg/jax_xc#38]
Hi there,

I am looking into the possibility of plugging `jax_xc` into our project [Grad DFT](https://github.com/XanaduAI/GradDFT) to expand the number of functionals we are able to deal with.

For this to work, we need to expose the energy densities rather than the XC energy itself. I.e, $\epsilon_{xc}(\mathbf{r})$.

Is there a way within `jax_xc` to do this?

**Comment by jackbaker1001** [comment]
Just tagging @mavenlin @DyeKuu for visibility.

**Comment by jackbaker1001** [comment]
I should have read the docs more fully. This seems easier to do than I thought. I'm going to close this and let you know if I was successful!

**Comment by DyeKuu** [comment]
Hi @jackbaker1001 , yeah I think you could try to hack https://github.com/sail-sg/jax_xc/tree/main/gen_repo/impl/prebuilt/unpol and apply the rules here https://github.com/sail-sg/jax_xc/blob/d26544994cf6a45719e4703d2885887714f2df68/gen_repo/impl/gen_py.py#L20-L50, and https://github.com/sail-sg/jax_xc/blob/d26544994cf6a45719e4703d2885887714f2df68/gen_repo/impl/python_template.jinja. 

Basically it takes those "function pieces" in `prebuilt`, apply the rules and fill in the template.

**Comment by mavenlin** [comment]
Something we haven't fully document is the experimental interface. We have a snippet in the readme. The following will do what you need,

```python
epsilon_xc=jax_xc.experimental.gga_x_pbe(rho)
```
rho is the density.

You can even get vxc

```python
# bwd mode
vxc = jax.grad(jax_xc.experimental.gga_x_pbe)(rho)
# or fwd mode
vxc_rho1 = jax.linearize(jax_xc.experimental.gga_x_pbe, rho)[1](rho1)
```
