### ISSUE TITLE
atol=2e-10 and rtol=2e-10 seems quite big for float64

### ISSUE THREAD

**Issue by mavenlin** [sail-sg/jax_xc#5]
Is this due to some extreme values in our test inputs?
Could we test with the density set to that of a gaussian type orbital?

**Comment by DyeKuu** [comment]
One of the major differences comes from the maple codegen side, for the same maple code, the Python code and the C code could exhibit difference details.

For example, in `gga_x_beefvdw` unpolarized code (the functional that deviates the biggest numerical error), there are 2 variables that sums up together, and each of it are also the sum of the other variables.  However, how to do the partition into the 2 variables are different in the Python code and the C code in libxc.

In python
```python
t87 = 0.4135586188014653875e4 * t50 * t49 - 0.5427777462637186032e4 * t50 * t53 + 0.40074935854432390114e5 * t50 * t56 - 0.29150193011493262292e5 * t50 * t60 + 0.90365611108522808258e5 * t50 * t63 - 0.16114215399846280595e6 * t50 * t66 - 0.13204466182182150467e6 * t50 * t48 + 0.2558947952623533461e6 * t50 * t71 - 0.32352403136049329184e6 * t50 * t46 + 0.18078200670879145336e6 * t50 * t47 - 0.12981481812794983922e6 * t50 * t59 + 0.56174007979372666951e5 * t50 * t44 + 0.27967048856303053872e6 * t50 * t45 - 0.16837084139014120539e6 * t50 + 0.70504541869034010051e5 * t48 * t71
t103 = 0.11313514630621233134e1 - 0.10276426607863824397e5 * t48 * t66 - 0.281024018056846299e4 * t49 + 0.22748997850816485208e4 * t60 - 0.20148245175625047025e5 * t53 + 0.37835396407252402359e4 * t56 - 0.44233229018433803622e3 * t48 - 0.61754786104528599731e3 * t63 + 0.86005730499279641299e2 * t66 - 0.72975787893717136018e1 * t47 + 0.30542034959315850168e2 * t71 - 0.69459735177638985466 * t46 - 0.38916037779196815969 * t45 + 0.52755620115589800943 * t59 + 0.37534251004296526981e-1 * t42
```

In C
```c
t78 = -0.69459735177638985466e0 * t45 + 0.52755620115589800943e0 * t47 - 0.38916037779196815969e0 * t44 - 0.44233229018433803622e3 * t50 - 0.61754786104528599731e3 * t52 + 0.37835396407252402359e4 * t54 - 0.72975787893717136018e1 * t56 + 0.30542034959315850168e2 * t58 + 0.86005730499279641299e2 * t60 - 0.5427777462637186032e4 * t64 + 0.4135586188014653875e4 * t63 * t66 - 0.29150193011493262292e5 * t70 + 0.40074935854432390114e5 * t72 + 0.90365611108522808258e5 * t74 - 0.16114215399846280595e6 * t76;
t102 = 0.11313514630621233134e1 - 0.13204466182182150467e6 * t79 + 0.2558947952623533461e6 * t81 - 0.32352403136049329184e6 * t83 + 0.18078200670879145336e6 * t85 - 0.12981481812794983922e6 * t87 + 0.56174007979372666951e5 * t89 + 0.27967048856303053872e6 * t91 - 0.10276426607863824397e5 * t93 - 0.16837084139014120539e6 * t63 - 0.281024018056846299e4 * t66 + 0.70504541869034010051e5 * t97 + 0.22748997850816485208e4 * t69 - 0.20148245175625047025e5 * t62 + 0.37534251004296526981e-1 * t41;
```

The coefficient `0.4135586188014653875e4` and `0.69459735177638985466` are partitioned into 2 variables in Python code while they are partitioned together in C code.

When given `r0=1` and `s0=1` as input, the 2 variables in Python are calculated as `4950.3740984881515` and `-4949.336203207162`, and in C they are `99989.78580149758` and `-99988.74790621664`, the sum of them gives `1.0378952809896873` and `1.0378952809405746`, the final result gives `-0.7665466583614658` and `-0.7665466583251933`, which is `3e-11`.

**Comment by mavenlin** [comment]
Feel like the misalignment can't even be called an error since it would require more analysis case by case on whether the C or Python code has a smaller numerical error, as compared to the analytical solution.
